Alfresco/alfresco-helm-charts

README.md
=> OPSEXP-1855 Add a quick overview in README

.github/workflows/pre-commit.yaml
Ref: OPSEXP-2004
Requires https://github.com/Alfresco/alfresco-build-tools/pull/239
=> OPSEXP-2004 Enable pre-commit auto-commit

.github/workflows/updatecli.yaml, updatecli.d/alfresco-common.tpl
=> OPSEXP-2003 Bump alfresco-common with updatecli

updatecli.d/alfresco-common.tpl
Fix for https://github.com/Alfresco/alfresco-helm-charts/actions/runs/4294482996/jobs/7483567767#step:5:100
=> Fix updatecli warning about pr action

charts/alfresco-search-service/Chart.yaml, charts/alfresco-search-service/README.md, charts/alfresco-search-service/templates/_helpers.tpl, charts/alfresco-search-service/values.yaml
=> OPSEXP-1853: move named template back in chart

charts/alfresco-search-service/Chart.lock, charts/alfresco-search-service/Chart.yaml, charts/alfresco-search-service/README.md, charts/alfresco-search-service/charts/alfresco-insight-zeppelin/Chart.lock, charts/alfresco-search-service/charts/alfresco-insight-zeppelin/Chart.yaml, charts/alfresco-search-service/charts/alfresco-insight-zeppelin/README.md, charts/alfresco-search-service/charts/alfresco-insight-zeppelin/templates/_helpers.tpl, charts/alfresco-search-service/charts/alfresco-insight-zeppelin/templates/config.yaml, charts/alfresco-search-service/charts/alfresco-insight-zeppelin/tests/config_test.yaml, charts/alfresco-search-service/tests/resources_test.yaml
Ref: OPSEXP-1853
As part of the search chart migration
=> OPSEXP-1853: fix repository config support for insight engine

charts/alfresco-sync-service/Chart.yaml, charts/alfresco-sync-service/README.md, charts/alfresco-sync-service/templates/svc-syncservice.yaml
=> OPSEXP-1854: Add missing service label selector

charts/alfresco-sync-service/Chart.yaml, charts/alfresco-sync-service/README.md, charts/alfresco-sync-service/values.yaml
Ref: OPSEXP-1854
avoid random issues when smoke tests run on acs-deployment
=> OPSEXP-1854: provide better default for test backend db

charts/alfresco-sync-service/Chart.yaml, charts/alfresco-sync-service/README.md, charts/alfresco-sync-service/templates/NOTES.txt, charts/alfresco-sync-service/templates/_helpers-db.tpl, charts/alfresco-sync-service/templates/_helpers-mq.tpl, charts/alfresco-sync-service/templates/_helpers.tpl, charts/alfresco-sync-service/templates/config-syncservice.yaml, charts/alfresco-sync-service/templates/deployment-syncservice.yaml, charts/alfresco-sync-service/templates/ingress.yaml, charts/alfresco-sync-service/templates/secret-database.yaml, charts/alfresco-sync-service/templates/secret-message-broker.yaml, charts/alfresco-sync-service/templates/svc-syncservice.yaml
=> OPSEXP-2071 use standard helmv3 labels for resources in sync chart

charts/alfresco-search-service/Chart.yaml, charts/alfresco-search-service/README.md, charts/alfresco-search-service/charts/alfresco-insight-zeppelin/README.md, charts/alfresco-search-service/charts/alfresco-insight-zeppelin/templates/config.yaml, charts/alfresco-search-service/charts/alfresco-insight-zeppelin/values.yaml, charts/alfresco-search-service/ci/default-values.yaml, charts/alfresco-search-service/templates/NOTES.txt, charts/alfresco-search-service/templates/ingress.yaml
=> OPSEXP-1853: handle externalPort gracefully

charts/alfresco-search-service/Chart.yaml, charts/alfresco-search-service/README.md, charts/alfresco-search-service/values.yaml
=> OPSEXP-2130 Bump search image tag to 2.0.7

charts/alfresco-search-enterprise/Chart.lock, charts/alfresco-search-enterprise/Chart.yaml, charts/alfresco-search-enterprise/README.md, charts/alfresco-search-enterprise/values.yaml
=> OPSEXP-2130 Bump ES image tag to 3.3.0

charts/alfresco-sync-service/Chart.lock, charts/alfresco-sync-service/Chart.yaml, charts/alfresco-sync-service/README.md, charts/alfresco-sync-service/values.yaml
=> OPSEXP-2130 Bump service sync to latest GA tag

charts/alfresco-search-service/Chart.yaml, charts/alfresco-search-service/README.md, charts/alfresco-search-service/templates/ingress.yaml, charts/alfresco-search-service/templates/secret-solr-jtoolopt.yaml, charts/alfresco-search-service/tests/ingress_test.yaml, charts/alfresco-search-service/tests/values/ingress.yaml, charts/alfresco-search-service/values.yaml
=> OPSEXP-2134: nginx annotation config means for solr

.github/workflows/updatecli.yaml
=> OPSEXP-2173 Fixup autocommit action with updatecli workflow

charts/alfresco-search-enterprise/Chart.yaml, charts/alfresco-search-enterprise/README.md, charts/alfresco-search-enterprise/values.yaml
=> OPSEXP-2173 Lint search enterprise values to avoid triggering updatecli reindent bug

charts/alfresco-search-enterprise/Chart.yaml, charts/alfresco-search-enterprise/README.md, charts/alfresco-search-enterprise/values.yaml
Requires https://github.com/Alfresco/alfresco-helm-charts/pull/59
Ref: OPSEXP-2173
I will raise more PRs once I fixed the updatecli configuration for each chart
=> OPSEXP-2173 Bump search enteprise tag

charts/alfresco-search-service/Chart.lock, charts/alfresco-search-service/Chart.yaml, charts/alfresco-search-service/README.md, charts/alfresco-search-service/charts/alfresco-insight-zeppelin/Chart.yaml, charts/alfresco-search-service/charts/alfresco-insight-zeppelin/README.md, charts/alfresco-search-service/charts/alfresco-insight-zeppelin/values.yaml
=> OPSEXP-2173 Bump insight-zeppelin to 2.0.7 and bump bugfix for search-service chart

charts/alfresco-ai-transformer/Chart.lock, charts/alfresco-ai-transformer/Chart.yaml, charts/alfresco-ai-transformer/README.md, charts/alfresco-ai-transformer/values.yaml
=> OPSEXP-2173 Update intelligence tag to 2.0.0

.github/workflows/updatecli.yaml, .gitignore, .pre-commit-config.yaml, matrix-targets.yaml
Ref: OPSEXP-2173
updatecli configs moved at https://github.com/Alfresco/alfresco-updatecli
=> OPSEXP-2173 Add updatecli pipeline to bump acs components

charts/alfresco-common/Chart.yaml, charts/alfresco-common/README.md, charts/alfresco-common/templates/_helpers-nginx.tpl, charts/alfresco-common/templates/_helpers-url.tpl
Ref: OPSEXP-2188
refactor to use from both share and repo
=> OPSEXP-2188: add nginx specific annotation to use from repo a share

charts/alfresco-share/Chart.lock, charts/alfresco-share/Chart.yaml, charts/alfresco-share/README.md, charts/alfresco-share/templates/config-share.yaml, charts/alfresco-share/templates/deployment-share.yaml, charts/alfresco-share/tests/cm_test.yaml, charts/alfresco-share/tests/deployment_test.yaml, charts/alfresco-share/values.yaml
Ref: OPSEXP-2188
mostly an RFC i particular regarding the structure of the charts values
=> OPSEXP-2188: narrow the usage of existingConfigMap for better integration

charts/alfresco-share/Chart.yaml, charts/alfresco-share/README.md, charts/alfresco-share/templates/ingress.yaml, charts/alfresco-share/tests/ingress_test.yaml
=> OPSEXP-2188: missing ingress class in share

charts/activemq/Chart.lock, charts/activemq/Chart.yaml, charts/activemq/README.md, charts/activemq/templates/deployment-activemq.yaml, charts/activemq/values.yaml
* Bump activemq image to 5.17
Ref: OPSEXP-1818
=> OPSEXP-1818 Trigger redeployment if rendered secret has changed

.checkov-values.yml, charts/alfresco-repository/Chart.yaml, charts/alfresco-repository/README.md, charts/alfresco-repository/templates/deployment.yaml, charts/alfresco-repository/templates/ingress.yaml, charts/alfresco-repository/tests/ingress_test.yaml
=> OPSEXP-1862: add proper repo ingress

charts/alfresco-repository/Chart.yaml, charts/alfresco-repository/README.md, charts/alfresco-repository/templates/deployment.yaml, charts/alfresco-repository/tests/deployment_test.yaml, charts/alfresco-repository/values.yaml
=> OPSEXP-1862: add support for license

charts/alfresco-repository/Chart.yaml, charts/alfresco-repository/README.md, charts/alfresco-repository/ci/default-values.yaml, charts/alfresco-repository/templates/configmap-message-broker.yaml, charts/alfresco-repository/templates/configmap.yaml, charts/alfresco-repository/templates/deployment.yaml, charts/alfresco-repository/templates/secret-message-broker.yaml, charts/alfresco-repository/tests/configmap_test.yaml, charts/alfresco-repository/tests/message-broker_test.yaml, charts/alfresco-repository/tests/values/test_values.yaml, charts/alfresco-repository/values.yaml
=> OPSEXP-1862: add message broker support

charts/alfresco-repository/Chart.yaml, charts/alfresco-repository/README.md, charts/alfresco-repository/ci/default-values.yaml, charts/alfresco-repository/templates/_helpers-checksums.tpl, charts/alfresco-repository/templates/configmap.yaml, charts/alfresco-repository/templates/deployment.yaml, charts/alfresco-repository/templates/secret-database.yaml, charts/alfresco-repository/tests/configmap_test.yaml, charts/alfresco-repository/tests/deployment_test.yaml, charts/alfresco-repository/tests/secrets_test.yaml, charts/alfresco-repository/tests/values/test_values.yaml, charts/alfresco-repository/values.yaml
=> OPSEXP-1862: misc improvements

charts/alfresco-common/Chart.lock, charts/alfresco-common/Chart.yaml, charts/alfresco-common/README.md
=> OPSEXP-2234 Release alfresco-common 2.1.0

charts/activemq/Chart.yaml, charts/activemq/README.md, charts/activemq/templates/deployment-activemq.yaml, charts/activemq/tests/deployment-activemq_test.yaml, charts/activemq/values.yaml
=> OPSEXP-2274 Support for registry authentication in activemq chart

.checkov-values.yml, charts/alfresco-search-enterprise/Chart.yaml, charts/alfresco-search-enterprise/README.md, charts/alfresco-search-enterprise/templates/_helpers-elasticsearch.tpl, charts/alfresco-search-enterprise/templates/_helpers.tpl, charts/alfresco-search-enterprise/templates/configmap-database.yaml, charts/alfresco-search-enterprise/templates/liveindexing-config.yaml, charts/alfresco-search-enterprise/templates/liveindexing-deployment.yaml, charts/alfresco-search-enterprise/templates/reindexing-config.yaml, charts/alfresco-search-enterprise/templates/reindexing-job.yaml, charts/alfresco-search-enterprise/templates/secret-database.yaml, charts/alfresco-search-enterprise/templates/secret-elasticsearch.yaml, charts/alfresco-search-enterprise/templates/secret-messagebroker.yaml, charts/alfresco-search-enterprise/tests/configmap-database_test.yaml, charts/alfresco-search-enterprise/tests/reindexing-job_test.yaml, charts/alfresco-search-enterprise/tests/reindexing_test.yaml, charts/alfresco-search-enterprise/tests/secret-database_test.yaml, charts/alfresco-search-enterprise/values.yaml
=> OPSEXP-2177 Generic database support for search enterprise

charts/alfresco-search-enterprise/Chart.lock, charts/alfresco-search-enterprise/Chart.yaml, charts/alfresco-search-enterprise/README.md, charts/alfresco-share/Chart.yaml, charts/alfresco-share/README.md, charts/alfresco-share/values.yaml, charts/alfresco-sync-service/Chart.lock, charts/alfresco-sync-service/Chart.yaml, charts/alfresco-sync-service/README.md, charts/alfresco-sync-service/values.yaml
=> OPSEXP-2311 Bump charts for cassiopeia release

updatecli-matrix-targets.yaml
=> OPSEXP-2311 Enable alfresco-repository as an updatecli target

charts/alfresco-repository/Chart.yaml, charts/alfresco-repository/README.md, charts/alfresco-repository/docs/keystores.md, charts/alfresco-repository/templates/configmap-repository.yaml, charts/alfresco-repository/templates/deployment.yaml
=> OPSEXP-2242: add custom keystores support

charts/alfresco-repository/Chart.yaml, charts/alfresco-repository/README.md, charts/alfresco-repository/docs/email.md, charts/alfresco-repository/templates/configmap-repository.yaml, charts/alfresco-repository/templates/deployment.yaml, charts/alfresco-repository/templates/service-smtp.yaml, charts/alfresco-repository/tests/mail_test.yaml, charts/alfresco-repository/values.yaml
=> OPSEXP-2242: enable inbound smtp service

charts/alfresco-common/Chart.yaml, charts/alfresco-common/README.md
=> OPSEXP-2364 Release alfresco-common 3.0.0

.github/workflows/lint-test.yaml
=> OPSEXP-2364 unittest to v0.3.6

charts/alfresco-repository/Chart.lock, charts/alfresco-repository/Chart.yaml, charts/alfresco-repository/README.md, charts/alfresco-repository/values.yaml, charts/alfresco-search-enterprise/Chart.yaml, charts/alfresco-search-enterprise/README.md, charts/alfresco-search-enterprise/values.yaml, charts/alfresco-search-service/Chart.yaml, charts/alfresco-search-service/README.md, charts/alfresco-search-service/values.yaml, charts/alfresco-share/Chart.yaml, charts/alfresco-share/README.md, charts/alfresco-share/values.yaml, charts/alfresco-sync-service/Chart.yaml, charts/alfresco-sync-service/README.md, charts/alfresco-sync-service/values.yaml, charts/alfresco-transform-service/Chart.yaml, charts/alfresco-transform-service/README.md, charts/alfresco-transform-service/values.yaml, updatecli-matrix-targets.yaml
=> OPSEXP-2364 Release charts for alfresco 23.1

charts/alfresco-search-service/Chart.yaml, charts/alfresco-search-service/README.md, charts/alfresco-search-service/templates/deployment.yaml, charts/alfresco-search-service/tests/deployment_test.yaml
Replace https://github.com/Alfresco/alfresco-helm-charts/pull/160
=> Add pod annotations to search service chart

charts/alfresco-search-enterprise/Chart.yaml, charts/alfresco-search-enterprise/README.md, charts/alfresco-search-enterprise/templates/liveindexing-deployment.yaml, charts/alfresco-search-enterprise/tests/liveindexing-deployment_test.yaml
=> OPSEXP-2435  Fix nodeSelector, affinity, tolerations in SE deployment

charts/alfresco-common/Chart.yaml, charts/alfresco-common/README.md, charts/alfresco-common/templates/_helpers-ats.tpl
=> OPSEXP-2293: add ATS common templates

charts/alfresco-ai-transformer/Chart.lock, charts/alfresco-ai-transformer/Chart.yaml, charts/alfresco-ai-transformer/README.md, charts/alfresco-ai-transformer/templates/config-sfs.yaml, charts/alfresco-ai-transformer/tests/confimap_test.yaml, charts/alfresco-search-enterprise/Chart.lock, charts/alfresco-search-enterprise/Chart.yaml, charts/alfresco-search-enterprise/README.md, charts/alfresco-search-enterprise/templates/_helpers-ats.tpl, charts/alfresco-search-enterprise/tests/configmaps_test.yaml
=> OPSEXP-2293: use ATS common named templates in ai & search ent charts

charts/alfresco-search-enterprise/Chart.yaml, charts/alfresco-search-enterprise/README.md, charts/alfresco-search-enterprise/templates/reindexing-job.yaml, charts/alfresco-search-enterprise/templates/statefulset-mediation.yaml, charts/alfresco-search-enterprise/tests/statefulset-mediation_test.yaml
=> OPSEXP-2435 Add nodeSelector/affinity/tolerations support in mediation statefulset

.github/workflows/lint-test.yaml
=> OPSEXP-2301 Bump to helm unittest plugin v.0.4.0

charts/alfresco-transform-service/Chart.yaml, charts/alfresco-transform-service/README.md, charts/alfresco-transform-service/values.yaml
=> OPSEXP-2301 Disable ci dependencies by default

charts/alfresco-ai-transformer/Chart.yaml, charts/alfresco-ai-transformer/README.md, charts/alfresco-ai-transformer/templates/_helpers-name.tpl, charts/alfresco-ai-transformer/templates/config-aws.yaml, charts/alfresco-ai-transformer/templates/config-message-broker.yaml, charts/alfresco-ai-transformer/templates/config-sfs.yaml, charts/alfresco-ai-transformer/templates/deployment-ai-transformer.yaml, charts/alfresco-ai-transformer/templates/secret-aws.yaml, charts/alfresco-ai-transformer/templates/secret-messagebroker.yaml, charts/alfresco-ai-transformer/tests/confimap_test.yaml, charts/alfresco-ai-transformer/tests/deployment-ai-tranformer_test.yaml
* Refactor in named template for resource names
Ref: OPSEXP-2293
=> OPSEXP-2293 Fix wrong resource name for broker url

charts/alfresco-sync-service/Chart.yaml, charts/alfresco-sync-service/README.md, charts/alfresco-sync-service/values.yaml
=> OPSEXP-2300: add ci tag in sync chart's values file

charts/alfresco-sync-service/Chart.yaml, charts/alfresco-sync-service/README.md, charts/alfresco-sync-service/values.yaml
=> OPSEXP-2324: shrink sync db pool to allow for several pods on smaller pg server

charts/alfresco-connector-ms365/Chart.lock, charts/alfresco-connector-ms365/Chart.yaml, charts/alfresco-connector-ms365/README.md
=> OPSEXP-2444 Release v0.5.0 ms365 chart

charts/alfresco-search-enterprise/Chart.lock, charts/alfresco-search-enterprise/Chart.yaml, charts/alfresco-search-enterprise/README.md, charts/alfresco-search-enterprise/README.md.gotmpl
=> OPSEXP-2444: Bump search enterprise chart to 3.1.0

charts/alfresco-sync-service/Chart.lock, charts/alfresco-sync-service/Chart.yaml, charts/alfresco-sync-service/README.md
=> OPSEXP-2444 Bump dependencies in sync chart and release 5.0.0

charts/alfresco-ai-transformer/Chart.yaml, charts/alfresco-ai-transformer/README.md, charts/alfresco-ai-transformer/templates/deployment-ai-transformer.yaml, charts/alfresco-ai-transformer/tests/deployment-ai-tranformer_test.yaml
=> OPSEXP-2440: alfresco-ai-transformer - fix wrong env vars for mq boker

charts/alfresco-transform-service/Chart.yaml, charts/alfresco-transform-service/README.md
=> OPSEXP-2444 Bump ats chart to 1.0.0

charts/alfresco-search-service/Chart.yaml, charts/alfresco-search-service/README.md, charts/alfresco-search-service/templates/ingress.yaml, charts/alfresco-search-service/tests/ingress_test.yaml, charts/alfresco-search-service/values.yaml
=> OPSEXP-2488 Configurable ingressClassName in search services chart

charts/alfresco-share/Chart.yaml, charts/alfresco-share/README.md, charts/alfresco-share/ci/default-values.yaml, charts/alfresco-share/templates/_helpers-name.tpl, charts/alfresco-share/templates/configmap-custom-application-context.yaml, charts/alfresco-share/templates/deployment.yaml, charts/alfresco-share/templates/ingress.yaml, charts/alfresco-share/templates/rbac.yaml, charts/alfresco-share/templates/service-hz.yaml, charts/alfresco-share/tests/configmap-custom-application-context_test.yaml, charts/alfresco-share/tests/configmap_test.yaml, charts/alfresco-share/tests/deployment_test.yaml, charts/alfresco-share/tests/ingress_test.yaml, charts/alfresco-share/tests/rbac_test.yaml, charts/alfresco-share/tests/service-hz_test.yaml, charts/alfresco-share/tests/service_test.yaml, charts/alfresco-share/values.yaml
=> OPSEXP-2452 Support share clustering

.checkov-values.yml, .checkov.yml, .github/workflows/checkov.yml, .pre-commit-config.yaml
It's not actually fixing the silent fail in helm rendering but at least we get issues nicely reported in the UI and we prevent issues related to using it with pre-commit
Ref: OPSEXP-2500
=> OPSEXP-2500 Switch to checkov action

charts/activemq/Chart.yaml, charts/activemq/README.md, charts/activemq/templates/deployment-activemq.yaml, charts/alfresco-ai-transformer/Chart.yaml, charts/alfresco-ai-transformer/README.md, charts/alfresco-ai-transformer/templates/deployment-ai-transformer.yaml, charts/alfresco-ai-transformer/templates/svc-ai-transformer.yaml, charts/alfresco-connector-ms365/Chart.yaml, charts/alfresco-connector-ms365/README.md, charts/alfresco-connector-ms365/templates/deployment-connector-ms365.yaml, charts/alfresco-connector-msteams/Chart.yaml, charts/alfresco-connector-msteams/README.md, charts/alfresco-connector-msteams/templates/deployment-connector-msteams.yaml, charts/alfresco-repository/Chart.yaml, charts/alfresco-repository/README.md, charts/alfresco-repository/templates/deployment.yaml, charts/alfresco-search-enterprise/Chart.yaml, charts/alfresco-search-enterprise/README.md, charts/alfresco-search-enterprise/templates/reindexing-job.yaml, charts/alfresco-share/Chart.yaml, charts/alfresco-share/README.md, charts/alfresco-share/templates/service-hz.yaml, charts/alfresco-share/templates/service.yaml
=> OPSEXP-2438 Fix missing labels for pods improperly using only selectorLabels

charts/alfresco-search-enterprise/Chart.yaml, charts/alfresco-search-enterprise/README.md, charts/alfresco-search-enterprise/ci/default-values.yaml, charts/alfresco-search-enterprise/templates/reindexing-job.yaml
=> OPSEXP-2449 Fixup yaml linting issue in search enterprise reindex job

charts/alfresco-sync-service/Chart.yaml, charts/alfresco-sync-service/README.md, charts/alfresco-sync-service/templates/_helpers-name.tpl, charts/alfresco-sync-service/templates/configmap-hazelcast.yaml, charts/alfresco-sync-service/templates/configmap-syncservice.yaml, charts/alfresco-sync-service/templates/deployment.yaml, charts/alfresco-sync-service/templates/rbac.yaml, charts/alfresco-sync-service/templates/service-hz.yaml, charts/alfresco-sync-service/tests/configmap-hazelcast_test.yaml, charts/alfresco-sync-service/tests/deployment_test.yaml, charts/alfresco-sync-service/tests/rbac_test.yaml, charts/alfresco-sync-service/tests/service-hz_test.yaml, charts/alfresco-sync-service/values.yaml
=> OPSEXP-2454 Support sync clustering

charts/alfresco-sync-service/Chart.yaml, charts/alfresco-sync-service/README.md, charts/alfresco-sync-service/templates/_helpers-name.tpl
=> OPSEXP-2454 Fix cluster role binding name

charts/alfresco-common/Chart.yaml, charts/alfresco-common/templates/_helpers-security.tpl
Ref: OPSEXP-2502
https://docs.bridgecrew.io/docs/bc_k8s_6
=> OPSEXP-2502 Remove unnecessary drop cap for net_raw

charts/alfresco-adf-app/Chart.yaml, charts/alfresco-adf-app/README.md, charts/alfresco-ai-transformer/Chart.yaml, charts/alfresco-ai-transformer/README.md, charts/alfresco-ai-transformer/values.yaml, charts/alfresco-repository/Chart.yaml, charts/alfresco-repository/README.md, charts/alfresco-repository/values.yaml, charts/alfresco-search-service/Chart.yaml, charts/alfresco-search-service/README.md, charts/alfresco-search-service/values.yaml, charts/alfresco-share/Chart.yaml, charts/alfresco-share/README.md, charts/alfresco-share/values.yaml, charts/alfresco-transform-service/Chart.yaml, charts/alfresco-transform-service/README.md, charts/alfresco-transform-service/values.yaml
=> OPSEXP-2519 Bump version for 23.2 release

charts/alfresco-repository/Chart.yaml, charts/alfresco-repository/README.md, charts/alfresco-repository/ci/default-values.yaml, charts/alfresco-repository/templates/deployment.yaml
=> OPSEXP-2481: alfresco-repository - fix repo init container

charts/alfresco-repository/Chart.yaml, charts/alfresco-repository/README.md, charts/alfresco-repository/docs/autoscaling.md, charts/alfresco-repository/templates/deployment.yaml, charts/alfresco-repository/templates/hpa.yaml, charts/alfresco-repository/tests/deployment_test.yaml, charts/alfresco-repository/tests/hpa_test.yaml, charts/alfresco-repository/values.yaml
Ref: OPSEXP-2524
Check Confluence link in JIRA for details of experimantation
=> OPSEXP-2524: alfresco-repository - introduce optional hpa

charts/alfresco-search-enterprise/Chart.yaml, charts/alfresco-search-enterprise/README.md, charts/alfresco-search-enterprise/values.yaml
=> OPSEXP-2574 Update search enterprise version tags to new secure image.

charts/alfresco-connector-ms365/Chart.yaml, charts/alfresco-connector-ms365/README.md, charts/alfresco-connector-ms365/templates/ingress-conector-ms365.yaml, charts/alfresco-connector-ms365/tests/ingress-conector-ms365_test.yaml, charts/alfresco-connector-msteams/Chart.yaml, charts/alfresco-connector-msteams/README.md, charts/alfresco-connector-msteams/templates/ingress-connector-msteams.yaml, charts/alfresco-connector-msteams/tests/ingress-connector-msteams_test.yaml
=> OPSEXP-2488 Fix apiVersion of ingresses for msteams and ms365

charts/alfresco-process-services/Chart.yaml, charts/alfresco-process-services/README.md, charts/alfresco-process-services/templates/ingress-admin.yaml, charts/alfresco-process-services/templates/ingress-aps.yaml, charts/alfresco-process-services/tests/ingress_test.yaml, charts/alfresco-process-services/values.yaml
=> OPSEXP-2592: alfresco-process-service - update ingress template to match other charts

charts/alfresco-process-services/Chart.yaml, charts/alfresco-process-services/README.md, charts/alfresco-process-services/docs/databases-configuration.md, charts/alfresco-process-services/docs/elasticsearch-configuration.md
Ref: OPSEXP-146
Requires: #258
=> OPSEXP-146: add documentation on how to configure APS databases

charts/alfresco-activiti-admin/Chart.yaml, charts/alfresco-activiti-admin/README.md, charts/alfresco-activiti-admin/templates/deployment.yaml, charts/alfresco-activiti-admin/tests/deployment_test.yaml, charts/alfresco-activiti-admin/values.yaml, charts/alfresco-activiti/Chart.yaml, charts/alfresco-activiti/README.md, charts/alfresco-activiti/templates/deployment.yaml, charts/alfresco-activiti/tests/deployment_test.yaml, charts/alfresco-activiti/values.yaml
Ref: OPSEXP-2529
Mostly useful for umbrella charts
=> OPSEXP-2529: add general pupose confgmaps for activiti charts (envFrom)

charts/alfresco-activiti-admin/Chart.yaml, charts/alfresco-activiti-admin/README.md, charts/alfresco-activiti-admin/templates/_helpers-rest.tpl, charts/alfresco-activiti-admin/templates/configmap.yaml, charts/alfresco-activiti-admin/values.yaml
=> OPSEXP-2529: ACTIVITI-5113 workaround

charts/alfresco-activiti-admin/Chart.yaml, charts/alfresco-activiti-admin/README.md, charts/alfresco-activiti-admin/templates/_helpers-workarounds.tpl, charts/alfresco-activiti-admin/templates/configmap.yaml, charts/alfresco-activiti/Chart.yaml, charts/alfresco-activiti/README.md, charts/alfresco-activiti/ci/default-values.yaml, charts/alfresco-activiti/templates/_helpers-workarounds.tpl, charts/alfresco-activiti/templates/configmap.yaml, charts/alfresco-activiti/values.yaml
=> OPSEXP-2529: activiti-5113 workaround for elasticsearch support in activiti app

charts/alfresco-activiti-admin/Chart.yaml, charts/alfresco-activiti-admin/README.md, charts/alfresco-activiti-admin/values.yaml, charts/alfresco-activiti/Chart.yaml, charts/alfresco-activiti/README.md, charts/alfresco-activiti/values.yaml
=> OPSEXP-2529: add resources default for activiti charts

charts/alfresco-ai-transformer/Chart.lock, charts/alfresco-ai-transformer/Chart.yaml, charts/alfresco-ai-transformer/README.md, charts/alfresco-search-enterprise/Chart.lock, charts/alfresco-search-enterprise/Chart.yaml, charts/alfresco-search-enterprise/README.md, charts/alfresco-sync-service/Chart.lock, charts/alfresco-sync-service/Chart.yaml, charts/alfresco-sync-service/README.md, charts/alfresco-transform-service/Chart.lock, charts/alfresco-transform-service/Chart.yaml, charts/alfresco-transform-service/README.md
=> OPSEXP-2630 Bump activemq chart version in downstream charts

charts/alfresco-activiti-admin/Chart.yaml, charts/alfresco-activiti-admin/README.md, charts/alfresco-activiti-admin/values.yaml, charts/alfresco-activiti/Chart.yaml, charts/alfresco-activiti/README.md, charts/alfresco-activiti/values.yaml
=> OPSEXP-2628 Disable workaround for aps charts bug prior to version 24.2

scripts/kube2mermaid.py
Ref: OPSEXP-2608
nothing special but at least you get a list of resources without risking to lose some
=> OPSEXP-2608 Add script to kickstart mermaid diagrams from kubernetes manifests

charts/alfresco-transform-service/docs/autoscaling.md
=> OPSEXP-2528 Add basic cpu based auto scaling doc for ATS

.github/workflows/docs.yml, charts/alfresco-transform-service/docs/autoscaling.md, docs/guides/alfresco-transform-service.md
Ref: OPSEXP-2529
requires https://github.com/Alfresco/jekyll-build-tools/pull/15
=> OPSEXP-2528: fix jekyll workflow

charts/alfresco-activiti/Chart.yaml, charts/alfresco-activiti/README.md, charts/alfresco-activiti/values.yaml
Ref: OPSEXP-2664
(APS admin dev images are not released so we'll have to wait for release before we can do/test it OPSEXP-2702)
=> OPSEXP-2664: update APS app probes endpoints

charts/alfresco-connector-ms365/Chart.yaml, charts/alfresco-connector-ms365/README.md, charts/alfresco-connector-ms365/templates/deployment-connector-ms365.yaml, charts/alfresco-connector-ms365/tests/deployment-connector-ms365_test.yaml, charts/alfresco-connector-ms365/values.yaml, charts/alfresco-connector-msteams/Chart.yaml, charts/alfresco-connector-msteams/README.md, charts/alfresco-connector-msteams/templates/deployment-connector-msteams.yaml, charts/alfresco-connector-msteams/tests/deployment-connector-msteams_test.yaml, charts/alfresco-connector-msteams/values.yaml
=> OPSEXP-2785 Add completely customizable probes for connector charts

charts/alfresco-transform-service/Chart.yaml, charts/alfresco-transform-service/README.md, charts/alfresco-transform-service/templates/deployment-filestore.yaml, charts/alfresco-transform-service/tests/deployment-filestore_test.yaml, charts/alfresco-transform-service/values.yaml
=> OPSEXP-2504 Configurable strategy.type for filestore

charts/activemq/Chart.yaml, charts/activemq/README.md, charts/activemq/values.yaml
=> OPSEXP-2778 Release activemq 5.18.5

charts/alfresco-activiti-admin/Chart.yaml, charts/alfresco-activiti-admin/README.md, charts/alfresco-activiti-admin/tests/deployment_test.yaml, charts/alfresco-activiti-admin/values.yaml
=> OPSEXP-2702 Update APS admin probes endpoints

charts/alfresco-share/Chart.lock, charts/alfresco-share/Chart.yaml, charts/alfresco-share/README.md, charts/alfresco-share/ci/default-values.yaml, charts/alfresco-share/tests/deployment_test.yaml
* Incorporate the fix in https://github.com/Alfresco/alfresco-helm-charts/pull/365
=> Release share chart v1.1.1

charts/alfresco-connector-ms365/Chart.yaml, charts/alfresco-connector-ms365/README.md, charts/alfresco-connector-ms365/templates/ingress-conector-ms365.yaml, charts/alfresco-connector-ms365/tests/ingress-conector-ms365_test.yaml, charts/alfresco-connector-ms365/values.yaml, charts/alfresco-connector-msteams/Chart.yaml, charts/alfresco-connector-msteams/README.md, charts/alfresco-connector-msteams/templates/ingress-connector-msteams.yaml, charts/alfresco-connector-msteams/tests/ingress-connector-msteams_test.yaml, charts/alfresco-connector-msteams/values.yaml
=> OPSEXP-2482 Replace deprecated annotations with spec.ingressClassName

.github/workflows/kics.yml
=> OPSEXP-2121 Add kics scan

charts/alfresco-connector-hxi/Chart.yaml, charts/alfresco-connector-hxi/README.md, charts/alfresco-connector-hxi/templates/job-connector-hxi-bulk-ingester.yaml, charts/alfresco-connector-hxi/tests/job-connector-hxi-bulk-ingester_test.yaml, charts/alfresco-connector-hxi/values.yaml, charts/alfresco-repository/Chart.yaml, charts/alfresco-repository/README.md, charts/alfresco-repository/templates/deployment.yaml, charts/alfresco-repository/tests/deployment_test.yaml, charts/alfresco-repository/values.yaml, charts/alfresco-search-enterprise/Chart.yaml, charts/alfresco-search-enterprise/README.md, charts/alfresco-search-enterprise/templates/reindexing-job.yaml, charts/alfresco-search-enterprise/tests/reindexing-job_test.yaml, charts/alfresco-search-enterprise/values.yaml
=> OPSEXP-2900 Configurable init containers

charts/alfresco-adf-app/Chart.yaml, charts/alfresco-adf-app/README.md, charts/alfresco-adf-app/values.yaml
Fix https://github.com/Alfresco/alfresco-helm-charts/security/code-scanning/3023
=> Run container on high uid by default

charts/activemq/Chart.lock, charts/activemq/Chart.yaml, charts/activemq/README.md, charts/activemq/values.yaml
=> OPSEXP-2938 Bump activemq to 5.18.6

charts/alfresco-connector-hxi/Chart.yaml, charts/alfresco-connector-hxi/README.md, charts/alfresco-connector-hxi/ci/default-values.yaml, charts/alfresco-connector-hxi/values.yaml
=> OPSEXP-2938 Bump HxI Connector version for Orion release

README.md, _config.yml, charts/alfresco-repository/Chart.yaml, charts/alfresco-repository/README.md, charts/alfresco-repository/docs/email.md, charts/alfresco-repository/docs/enterprise-license.md, charts/alfresco-repository/values.yaml
=> OPSEXP-2933 Point links to support.hyland.com

.github/workflows/release.yaml, charts/alfresco-audit-storage/Chart.lock, charts/alfresco-audit-storage/Chart.yaml, charts/alfresco-audit-storage/README.md, charts/alfresco-audit-storage/ci/default-values.yaml, charts/alfresco-search-enterprise/Chart.lock, charts/alfresco-search-enterprise/Chart.yaml, charts/alfresco-search-enterprise/README.md, charts/alfresco-search-enterprise/ci/default-values.yaml, ct.yaml
=> OPSEXP-2950 Use bitnami/elasticsearch helm chart dependencies

.github/workflows/lint-test.yaml, charts/alfresco-search-service/Chart.lock, charts/alfresco-search-service/Chart.yaml, charts/alfresco-search-service/README.md, charts/alfresco-search-service/charts/alfresco-insight-zeppelin/Chart.lock, charts/alfresco-search-service/charts/alfresco-insight-zeppelin/Chart.yaml, charts/alfresco-search-service/charts/alfresco-insight-zeppelin/README.md, charts/alfresco-search-service/charts/alfresco-insight-zeppelin/tests/config_test.yaml, charts/alfresco-search-service/charts/alfresco-insight-zeppelin/tests/deployment_test.yaml, charts/alfresco-search-service/charts/alfresco-insight-zeppelin/tests/ingress_test.yaml, charts/alfresco-search-service/charts/alfresco-insight-zeppelin/tests/values/test_values.yaml, ct.yaml
=> OPSEXP-2249 Enable helm unittest with subcharts

charts/alfresco-common/Chart.yaml, charts/alfresco-common/README.md
=> OPSEXP-3034 Release alfresco-common chart v4.0.0

charts/activemq/Chart.lock, charts/activemq/Chart.yaml, charts/activemq/README.md
=> OPSEXP-3034 Bump activemq chart version v3.6.1

charts/alfresco-repository/Chart.yaml, charts/alfresco-repository/README.md, charts/alfresco-repository/values.yaml, charts/alfresco-share/Chart.yaml, charts/alfresco-share/README.md, charts/alfresco-share/values.yaml
=> OPSEXP-3015: Add a time limit to proxied requests

.github/workflows/lint-test.yaml, .pre-commit-config.yaml
=> OPSEXP-3028: bump KinD to reflect EKS supported versions 

.github/updatecli-matrix-targets.yaml, .github/workflows/updatecli.yaml
=> OPSEXP-3114 Bump updatecli version

charts/alfresco-repository/Chart.yaml, charts/alfresco-repository/README.md, charts/alfresco-repository/values.yaml, charts/alfresco-search-service/Chart.yaml, charts/alfresco-search-service/README.md, charts/alfresco-search-service/values.yaml, charts/alfresco-transform-service/Chart.yaml, charts/alfresco-transform-service/README.md, charts/alfresco-transform-service/values.yaml
Bump and uniform all the charts to the same version so it get pulled once.
OPSEXP-3190
=> OPSEXP-3190 Bump busybox to latest minor

.github/workflows/docs.yml
https://github.com/Alfresco/alfresco-helm-charts/actions/runs/14878563640/job/41780992705?pr=469#step:7:21
=> Fix docs workflow by ignoring 429 error codes

charts/activemq/Chart.yaml, charts/activemq/README.md, charts/activemq/values.yaml, charts/alfresco-repository/Chart.yaml, charts/alfresco-repository/README.md, charts/alfresco-repository/docs/email.md, charts/alfresco-repository/docs/enterprise-license.md, charts/alfresco-repository/values.yaml
=> OPSEXP-3218 Bump repository chart with docs fix and activemq chart with tag update

charts/alfresco-ai-transformer/Chart.lock, charts/alfresco-ai-transformer/Chart.yaml, charts/alfresco-ai-transformer/README.md, charts/alfresco-audit-storage/Chart.lock, charts/alfresco-audit-storage/Chart.yaml, charts/alfresco-audit-storage/README.md, charts/alfresco-connector-hxi/Chart.lock, charts/alfresco-connector-hxi/Chart.yaml, charts/alfresco-connector-hxi/README.md, charts/alfresco-connector-hxi/values.yaml, charts/alfresco-search-enterprise/Chart.lock, charts/alfresco-search-enterprise/Chart.yaml, charts/alfresco-search-enterprise/README.md, charts/alfresco-sync-service/Chart.lock, charts/alfresco-sync-service/Chart.yaml, charts/alfresco-sync-service/README.md, charts/alfresco-transform-service/Chart.lock, charts/alfresco-transform-service/Chart.yaml, charts/alfresco-transform-service/README.md
=> OPSEXP-3218 Bump charts and hxi image tags for Sagittarius release

charts/alfresco-search-enterprise/Chart.yaml, charts/alfresco-search-enterprise/README.md, charts/alfresco-search-enterprise/templates/configmap-elasticsearch.yaml, charts/alfresco-search-enterprise/tests/configmap-elasticsearch_test.yaml
=> OPSEXP-2368 Error on missing .search.url for search enterprise

charts/alfresco-activiti-admin/Chart.yaml, charts/alfresco-activiti-admin/README.md, charts/alfresco-activiti-admin/values.yaml, charts/alfresco-activiti/Chart.yaml, charts/alfresco-activiti/README.md, charts/alfresco-activiti/values.yaml
[OPSEXP-3351]
[OPSEXP-3351]: https://hyland.atlassian.net/browse/OPSEXP-3351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OPSEXP-3351 Bump activiti charts for Ursa release

.github/workflows/pre-commit.yaml, .pre-commit-config.yaml, charts/alfresco-ai-transformer/Chart.yaml, charts/alfresco-ai-transformer/README.md, charts/alfresco-ai-transformer/values.yaml, charts/alfresco-connector-ms365/Chart.yaml, charts/alfresco-connector-ms365/README.md, charts/alfresco-connector-ms365/values.yaml, charts/alfresco-connector-msteams/Chart.yaml, charts/alfresco-connector-msteams/README.md, charts/alfresco-connector-msteams/values.yaml, charts/alfresco-repository/Chart.yaml, charts/alfresco-repository/README.md, charts/alfresco-repository/values.yaml, charts/alfresco-search-enterprise/Chart.yaml, charts/alfresco-search-enterprise/README.md, charts/alfresco-search-enterprise/values.yaml, charts/alfresco-search-service/Chart.lock, charts/alfresco-search-service/Chart.yaml, charts/alfresco-search-service/README.md, charts/alfresco-search-service/charts/alfresco-insight-zeppelin/Chart.yaml, charts/alfresco-search-service/charts/alfresco-insight-zeppelin/README.md, charts/alfresco-search-service/charts/alfresco-insight-zeppelin/values.yaml, charts/alfresco-search-service/values.yaml, charts/alfresco-share/Chart.yaml, charts/alfresco-share/README.md, charts/alfresco-share/values.yaml, charts/alfresco-transform-service/Chart.yaml, charts/alfresco-transform-service/README.md, charts/alfresco-transform-service/values.yaml
OPSEXP-3349
requires:
* https://github.com/Alfresco/alfresco-updatecli/pull/66
=> OPSEXP-3349 Bump tags for Ursa Major release
