charts/activemq/Chart.yaml
charts/activemq/README.md
charts/activemq/templates/svc-activemq-broker.yaml
charts/activemq/templates/svc-activemq-web-console.yaml
charts/activemq/tests/deployment-activemq_test.yaml
charts/activemq/tests/pvc-activemq_test.yaml
charts/activemq/tests/svc-activemq_test.yaml

Ref: OPSEXP-1855
was not using the same named template used to build pod metadata and service discovery was broken

OPSEXP-1855 Fix activemq service selector construction

---

charts/alfresco-common/Chart.yaml
charts/alfresco-common/README.md
charts/alfresco-common/templates/_helpers-activemq.tpl

This can cause some weird behaviour since it's conflicting with https://github.com/Alfresco/alfresco-helm-charts/blob/main/charts/activemq/templates/_helpers.tpl#L13

OPSEXP-1855 Get rid of previous activemq.fullname template

---

.github/workflows/lint-test.yaml

See https://github.com/kubernetes-sigs/kind/releases/tag/v0.17.0
* add support for testing all charts via `ci-test-all` label

OPSEXP-1881 KinD tests with latest 1.24 tag

---

charts/alfresco-common/Chart.yaml
charts/alfresco-common/README.md
charts/alfresco-common/templates/_helpers-search.tpl

Ref: OPSEXP-1853
While making search chart independant I needed to put some named templates back into the new chart. So some cleanup is necessary to avoid conflicts

OPSEXP-1853: remove resource naming related named templates

---

charts/alfresco-sync-service/Chart.yaml
charts/alfresco-sync-service/README.md
charts/alfresco-sync-service/templates/_helpers.tpl
charts/alfresco-sync-service/templates/config-syncservice.yaml
charts/alfresco-sync-service/tests/repo_test.yaml
charts/alfresco-sync-service/values.yaml

acs-deployment approach requires to be able to expand repo service name from release name

OPSPEXP-1854: add a repo helper usable from parent chart

---

.github/workflows/updatecli.yaml

Ref: OPSEXP-2173
otherwise the n+1 run without merging will always fail pushing

OPSEXP-2173 Push force when pushing via workflow dispatch

---

charts/alfresco-connector-ms365/Chart.yaml
charts/alfresco-connector-ms365/README.md
charts/alfresco-connector-ms365/values.yaml
charts/alfresco-connector-msteams/Chart.yaml
charts/alfresco-connector-msteams/README.md
charts/alfresco-connector-msteams/values.yaml
charts/alfresco-sync-service/Chart.yaml
charts/alfresco-sync-service/README.md
charts/alfresco-sync-service/values.yaml

Ref: OPSEXP-2173
Produced by running the updatecli workflow against https://github.com/Alfresco/alfresco-helm-charts/pull/60
https://github.com/Alfresco/alfresco-helm-charts/actions/runs/5402416826/jobs/9813670656

OPSEXP-2173 Bump andromeda release image tags

---

charts/alfresco-transform-service/Chart.yaml
charts/alfresco-transform-service/README.md
charts/alfresco-transform-service/ci/default-values.yaml
charts/alfresco-transform-service/templates/secret-messagebroker.yaml
charts/alfresco-transform-service/values.yaml

Required to avoid issues such as: https://github.com/Alfresco/acs-deployment/actions/runs/5453623178/jobs/9922696450#step:4:31

OPSEXP-1861: allow using charts names overrides without installing the chart itself

---

charts/alfresco-common/Chart.yaml
charts/alfresco-common/README.md
charts/alfresco-common/templates/_helpers-url.tpl

allow for better integration in acs-deployment and useful when making repo a dedicated chart as well

OPSEXP-2188: pass whole context for better reusability in building urls

---

charts/alfresco-common/Chart.yaml
charts/alfresco-common/README.md
charts/alfresco-common/templates/_helpers-url.tpl

Ref: OPSEXP-2188
* fixes a problem with list length comparison
* add sanitizer to named templates
* returns default if none is present in input

OPSEXP-2188: improve url building template in alfresco-common

---

.checkov-values.yml
.checkov.yml
.pre-commit-config.yaml

Ref: OPSEXP-2077
* Add `verbose` which seems the only way to actually get some feedback if things get wrong again
* Make sure to execute checkov locally only for changed charts files
* Skip 3rd party charts and our library chart which can't be scan

OPSEXP-2077 Fixup Checkov not really linting all charts

---

charts/alfresco-common/Chart.yaml
charts/alfresco-common/README.md
charts/alfresco-common/templates/_helpers-activemq.tpl
charts/alfresco-common/templates/_helpers-checksums.tpl
charts/alfresco-common/templates/_helpers-image-pull-secrets.tpl
charts/alfresco-common/templates/_helpers-jdbc.tpl
charts/alfresco-common/templates/_helpers-nginx.tpl
charts/alfresco-common/templates/_helpers-persistence.tpl
charts/alfresco-common/templates/_helpers-security.tpl
charts/alfresco-common/templates/_helpers-url.tpl

Ref: OPSEXP-18962
Ensure backward compatibility.
Tested backward compat by locally running helm template rendition and unittest for acs-deployment 
Created OPSEXP-2227 OPSEXP-2228 to deprecate and remove old names

OPSEXP-1862: move named tpl in alfresco-common

---

charts/alfresco-repository/Chart.lock
charts/alfresco-repository/Chart.yaml
charts/alfresco-repository/README.md
charts/alfresco-repository/templates/_helpers-database.tpl
charts/alfresco-repository/templates/configmap-repository.yaml
charts/alfresco-repository/templates/deployment.yaml
charts/alfresco-repository/tests/configmap_test.yaml
charts/alfresco-repository/tests/deployment_test.yaml
charts/alfresco-repository/values.yaml

OPSEXP-2242: allow jdbc prefix in repo url

---

charts/alfresco-repository/Chart.yaml
charts/alfresco-repository/README.md
charts/alfresco-repository/templates/deployment.yaml
charts/alfresco-repository/tests/deployment_test.yaml
charts/alfresco-repository/values.yaml

Ref: OPSEXP-2242: Needed in order to pass sensitive data (liked to a specific feature or config, e.g. smtp password) from a parent chart without checking whether the eature is enabled in subchart.
Open to discussion.

OPSEXP-2242: make repository secrets optional

---

charts/alfresco-search-enterprise/Chart.yaml
charts/alfresco-search-enterprise/README.md
charts/alfresco-search-enterprise/templates/reindexing-job.yaml

OPSEXP-2298: fix reindexing repository variable name

---

charts/alfresco-search-enterprise/Chart.yaml
charts/alfresco-search-enterprise/README.md
charts/alfresco-search-enterprise/templates/reindexing-job.yaml

Ref: OPSEXP-2298
looks like the `$(VAR)` notation in `spec.template.spec.containers[].args` does not work in shell and just creates a subshell instead (as it would in a regular shell env).
Tricked by https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/#using-environment-variables-inside-of-your-config

OPSEXP-2298: fixup search ernterprise chart - 3.0.0-alpha.4

---

charts/alfresco-search-enterprise/Chart.lock
charts/alfresco-search-enterprise/Chart.yaml
charts/alfresco-search-enterprise/README.md
charts/alfresco-search-enterprise/ci/default-values.yaml
charts/alfresco-search-enterprise/templates/_helpers-elasticsearch.tpl
charts/alfresco-search-enterprise/templates/configmap-elasticsearch.yaml
charts/alfresco-search-enterprise/templates/liveindexing-deployment.yaml
charts/alfresco-search-enterprise/templates/reindexing-job.yaml
charts/alfresco-search-enterprise/templates/secret-elasticsearch.yaml
charts/alfresco-search-enterprise/tests/liveindexing-deployment_test.yaml
charts/alfresco-search-enterprise/tests/reindexing-job_test.yaml
charts/alfresco-search-enterprise/tests/secret-elasticsearch_test.yaml
charts/alfresco-search-enterprise/tests/values/embedded-charts-values.yaml
charts/alfresco-search-enterprise/values.yaml

OPSEXP-2298: allow elasticsearch configuration using the same existingResource or values approach

---

charts/alfresco-common/Chart.yaml
charts/alfresco-common/README.md
charts/alfresco-common/templates/_helpers-jdbc.tpl

Ref: OPSEXP-2297
That function so far is only used in `alfresco-repository` chart (PR coming)

OPSEXP-2297: change alfresco-common.db.port named template param to a single str

---

.github/workflows/updatecli.yaml
updatecli-matrix-targets.yaml
updatecli.d/default.yaml

OPSEXP-2364 Bump to updatecli v0.65.1 and workflow enhancements

---

charts/activemq/Chart.lock
charts/activemq/Chart.yaml
charts/activemq/README.md
charts/activemq/templates/deployment-activemq.yaml
charts/activemq/values.yaml

OPSEXP-2292 Review and align chart activemq with newer principals

---

.pre-commit-config.yaml
scripts/charts.sh

OPSEXP-2364 Ensure release charts doesn't have pre-release dependencies

---

docs/README.md

OPSEXP-2364 Add release docs

---

charts/alfresco-repository/Chart.yaml
charts/alfresco-repository/README.md
charts/alfresco-repository/templates/deployment.yaml
charts/alfresco-repository/tests/deployment_test.yaml

Ref: OPSEXP-2435
```
helm template . --set alfresco-repository.nodeSelector.test=value
Error: YAML parse error on alfresco-content-services/charts/alfresco-repository/templates/deployment.yaml: error converting YAML to JSON: yaml: line 248: mapping values are not allowed in this context
Use --debug flag to render out invalid YAML
```

OPSEXP-2435 Fix nodeSelector configuration in alfresco-repository

---

charts/alfresco-search-service/Chart.yaml
charts/alfresco-search-service/README.md
charts/alfresco-search-service/templates/deployment.yaml
charts/alfresco-search-service/tests/deployment_test.yaml

Mainly useful for older search/acs versions which doesn't support preshared secret.
Ref: OPSEXP-2291

OPSEXP-2291 Repository secret should be optional in search service chart

---

.pre-commit-config.yaml
docs/README.md

OPSEXP-2444 Strict kubeconform from k8s 1.25

---

charts/alfresco-common/Chart.yaml
charts/alfresco-common/README.md
charts/alfresco-common/templates/_helpers-ats.tpl

Ref: OPSEXP-2440
Other charts lived nicely with the trailing `/`but ai-transformer complains with 404 errors

OPSEXP-2440: alfresco-common - remove trailing slash from SFS_URL

---

charts/alfresco-repository/Chart.yaml
charts/alfresco-repository/README.md
charts/alfresco-repository/templates/ingress.yaml
charts/alfresco-repository/tests/ingress_test.yaml
charts/alfresco-repository/values.yaml

- Drop support for previous apiVersions
Ref: [OPSEXP-2488](https://alfresco.atlassian.net/browse/OPSEXP-2488)
[OPSEXP-2488]: https://alfresco.atlassian.net/browse/OPSEXP-2488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OPSEXP-2488 Configurable ingress class in repository chart

---

.github/workflows/docs.yml
_config.yml
charts/alfresco-repository/docs/subsystems.md

OPSEXP-2620 Enable html validation in docs workflow

---

charts/alfresco-transform-service/Chart.yaml
charts/alfresco-transform-service/README.md
charts/alfresco-transform-service/templates/deployment-filestore.yaml
charts/alfresco-transform-service/tests/deployment-filestore_test.yaml

```
Error: INSTALLATION FAILED: 1 error occurred:
* Deployment.apps "acs-filestore" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'
```
OPSEXP-2504

OPSEXP-2504 Avoid setting rollingUpdate when unnecessary in filestore

---

.github/workflows/pre-commit.yaml
charts/alfresco-common/Chart.yaml
charts/alfresco-common/README.md
charts/alfresco-common/templates/_helpers-url.tpl

According to the share-config.xml CSRF origins should be separated with  | and not ,

Fix csrf.origin url join for share-config

---

charts/alfresco-search-enterprise/Chart.yaml
charts/alfresco-search-enterprise/README.md
charts/alfresco-search-enterprise/ci/default-values.yaml
charts/alfresco-search-enterprise/templates/reindexing-job.yaml
charts/alfresco-search-enterprise/tests/reindexing-job_test.yaml
charts/alfresco-search-enterprise/values.yaml

OPSEXP-2654
The new default is to run it as post-install hook so it won't rerun on each upgrade if was cleaned up.
Optionally `reindexing.hookExecution` could be set to `post-upgrade` so that could mimic an on-demand execution by triggering together with an upgrade. In this case the job name got a rand appended to avoid clashes.
It can be set to false to restore the previous behavior.

OPSEXP-2654 Reindex job as configurable helm hook

---

charts/alfresco-repository/Chart.lock
charts/alfresco-repository/Chart.yaml
charts/alfresco-repository/README.md
charts/alfresco-repository/values.yaml
charts/alfresco-share/Chart.yaml
charts/alfresco-share/README.md
charts/alfresco-share/values.yaml

OPSEXP-2871 [repository] [share] Bump default values to latest 23.3.2 tag

---

charts/alfresco-search-service/Chart.lock
charts/alfresco-search-service/Chart.yaml
charts/alfresco-search-service/README.md
charts/alfresco-search-service/charts/alfresco-insight-zeppelin/Chart.yaml
charts/alfresco-search-service/charts/alfresco-insight-zeppelin/README.md
charts/alfresco-search-service/charts/alfresco-insight-zeppelin/values.yaml
charts/alfresco-search-service/values.yaml

OPSEXP-2874 Bump Insight Engine to 2.0.12

---

charts/alfresco-search-enterprise/Chart.yaml
charts/alfresco-search-enterprise/README.md
charts/alfresco-search-enterprise/values.yaml

OPSEXP-2885 Fix secret template bug in search enterprise correcting search username reference

---

charts/alfresco-common/Chart.yaml
charts/alfresco-common/README.md

OPSEXP-2984 Remove dependency to bitnami/common in alfresco-common chart

---

charts/alfresco-connector-ms365/Chart.lock
charts/alfresco-connector-ms365/Chart.yaml
charts/alfresco-connector-ms365/README.md
charts/alfresco-connector-ms365/templates/ingress-conector-ms365.yaml
charts/alfresco-connector-ms365/tests/ingress-conector-ms365_test.yaml
charts/alfresco-connector-ms365/values.yaml
charts/alfresco-connector-msteams/Chart.lock
charts/alfresco-connector-msteams/Chart.yaml
charts/alfresco-connector-msteams/README.md
charts/alfresco-connector-msteams/templates/ingress-connector-msteams.yaml
charts/alfresco-connector-msteams/tests/ingress-connector-msteams_test.yaml
charts/alfresco-connector-msteams/values.yaml
charts/alfresco-search-service/Chart.lock
charts/alfresco-search-service/Chart.yaml
charts/alfresco-search-service/README.md
charts/alfresco-search-service/charts/alfresco-insight-zeppelin/Chart.yaml
charts/alfresco-search-service/charts/alfresco-insight-zeppelin/README.md
charts/alfresco-search-service/charts/alfresco-insight-zeppelin/templates/ingress.yaml
charts/alfresco-search-service/charts/alfresco-insight-zeppelin/tests/ingress_test.yaml
charts/alfresco-search-service/charts/alfresco-insight-zeppelin/values.yaml
charts/alfresco-search-service/templates/ingress.yaml
charts/alfresco-search-service/tests/ingress_test.yaml
charts/alfresco-search-service/values.yaml
charts/alfresco-sync-service/Chart.lock
charts/alfresco-sync-service/Chart.yaml
charts/alfresco-sync-service/README.md
charts/alfresco-sync-service/templates/ingress.yaml
charts/alfresco-sync-service/tests/ingress_test.yaml
charts/alfresco-sync-service/values.yaml

OPSEXP-2984 Remove dependency on bitnami/common in charts by aligning ingress templates with common practices

---

charts/alfresco-sync-service/Chart.yaml
charts/alfresco-sync-service/README.md
charts/alfresco-sync-service/templates/ingress.yaml
charts/alfresco-sync-service/tests/ingress_test.yaml
charts/alfresco-sync-service/values.yaml

OPSEXP-2991 Change sync service ingress pathType to ImplementationSpecific

---

.pre-commit-config.yaml
charts/alfresco-adf-app/Chart.yaml
charts/alfresco-adf-app/README.md
charts/alfresco-adf-app/values.yaml

Bumping charts in https://github.com/Alfresco/alfresco-dockerfiles-bakery/pull/153 exposed this breaking change
uid/gid should match the ones of the upstream `nginxinc/nginx-unprivileged` image so the entrypoint customization script works as expected.
OPSEXP-3128

OPSEXP-3128 Fixup compatiblity with nginx-unprivileged images

---

charts/alfresco-search-enterprise/Chart.yaml
charts/alfresco-search-enterprise/README.md
charts/alfresco-search-enterprise/docs/truststore.md
charts/alfresco-search-enterprise/templates/deployment.yaml
charts/alfresco-search-enterprise/templates/reindexing-job.yaml
charts/alfresco-search-enterprise/templates/statefulset-mediation.yaml
charts/alfresco-search-enterprise/tests/envs_test.yaml
charts/alfresco-search-enterprise/tests/extras_test.yaml
docs/guides/alfresco-search-enterprise.md

Ref: OPSEXP-3225
Provides comprehensive instructions on how to mount a custom keystore (addresses #463 )

OPSEXP-3225: allow mounting extra volumes in search enterprise

---

charts/elastic/Chart.yaml
charts/elastic/README.md
charts/elastic/templates/elasticsearch-statefulset.yaml
charts/elastic/values.yaml

ref: OPSEXP-3486
Starting from 7.11 elastic manages jvm heap size automatically based on limits on resources: https://www.elastic.co/guide/en/cloud-on-k8s/1.9/k8s-jvm-heap-size.html
https://www.elastic.co/docs/reference/elasticsearch/jvm-settings#set-jvm-heap-size

OPSEXP-3486 Bump probes and remove jvm heap size setting for elastic chart
